# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libboost-graph-dev
  - sudo apt-get install -y libboost-regex-dev
  - sudo apt-get install -y libz-dev
  - sudo apt-get install -y libpthread-stubs0-dev

language: c++

matrix:
  include:
    - compiler: g++-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9 ALADDIN_HOME=$PWD BOOST_ROOT=/usr/include/boost
    - compiler: g++-4.8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
      env: COMPILER=g++-4.8 ALADDIN_HOME=$PWD BOOST_ROOT=/usr/include/boost
    - compiler: g++-4.7
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.7
      env: COMPILER=g++-4.7 ALADDIN_HOME=$PWD BOOST_ROOT=/usr/include/boost

script:
  - cd common && make -j4
  - cd ../unit-test && make test -j4

notifications:
  email:
    on_success: never
    on_failure: always
    recipients:
      - shao@eecs.harvard.edu
      - samxi@seas.harvard.edu
